# Generated by Django 3.2.20 on 2023-08-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeCategories',
        ),
    ]
